#!/usr/bin/bash

cyan=$(echo -en '\033[0;36m')
red=$(echo -en '\033[0;31m')
green=$(echo -en '\033[0;32m')
yellow=$(echo -en '\033[0;33m')
blue=$(echo -en '\033[0;34m')
magenta=$(echo -en '\033[0;35m')
white=$(echo -en '\033[0;37m')
clear=$(echo -en '\033[0m')

echo "${cyan}C${red}o${green}l${yellow}o${blue}r ${magenta}s${white}o${cyan}u${green}r${yellow}c${blue}e${magenta}d${red}!"
